# Generated by Django 4.0.3 on 2022-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_payments_created_at_alter_payments_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='paid',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('PAY', 'PAYPAL'), ('STR', 'STRIPS')], default=str, max_length=3),
            preserve_default=False,
        ),
    ]
